lib/job_board_web/router.ex
defmodule JobBoardWeb.Router do
  use JobBoardWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug JobBoard.CSPHeader
    plug JobBoardWeb.Plugs.AddSiteConfig
    plug JobBoardWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug(:fetch_session)
    plug :protect_from_forgery
    plug JobBoardWeb.Plugs.SetUser
  end

  if Mix.env == :dev do
    # If using Phoenix
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  scope "/", JobBoardWeb do
    pipe_through :browser # Use the default browser stack

    get "/", JobController, :index
    resources "/jobs", JobController
    get "/jobs/:id/outbound", JobController, :outbound
    resources "/users", UserController, only: [:index, :new, :create, :show, :edit, :update, :delete]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/roles", RoleController
    resources "/states", StateController
    resources "/cities", CityController
    resources "/password", PasswordController
    resources "/siteconfigs", ConfigController
    get "/reset-password", PasswordController, :reset
    get "/contact", PageController, :contact
    get "/about", PageController, :about
    get "/privacy", PageController, :privacy
    get "/construction", PageController, :construction
    get "/terms", PageController, :terms
    get "/verify", UserController, :verify_email
    get "/reverify", UserController, :resend_verification


  end

  # Other scopes may use custom stacks.
  scope "/api", JobBoardWeb do
    pipe_through :api

    resources "/jobs", JobAPIController
    post("/sessions/sign_in", SessionAPIController, :sign_in)
    get("/sessions/csrftoken", SessionAPIController, :csrf_token)
    post("/jobs/create", JobAPIController, :create)
  end
end

lib/job_board_web/views/layout_view.ex
defmodule JobBoardWeb.LayoutView do
  use JobBoardWeb, :view
  alias Number.Currency
  alias JobBoardWeb.Router.Helpers, as: Routes

  def get_version() do
    {:ok, vsn} = :application.get_key(:job_board, :vsn)
    List.to_string(vsn)
  end

  def get_post_price(conn) do
    conn.assigns.config.post_price / 100
    |> Currency.number_to_currency
  end

  def get_post_link_text(conn) do
    "Post a Job for #{get_post_price(conn)}"
  end

  def get_site_name(conn) do
    conn.assigns.config.site_name
  end

  def get_site_slug(conn) do
    conn.assigns.config.site_slug
  end

  def get_current_url(conn) do
    Routes.url(conn)
  end
end

lib/job_board_web/templates/layout/app.html.eex
<%= render "header.html", conn: @conn, pagetitle: @pagetitle %>    
      <main role="main">
        <div class="container">
          <%= unless is_nil(get_flash(@conn, :info)) do %>
            <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
          <% end %>
          <%= unless is_nil(get_flash(@conn, :error)) do %>
            <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
          <% end %>
          <div class="main-content">
            <%= render @view_module, @view_template, assigns %>
          </div>
        </div> <!-- /container -->
        <div class="push"></div>
      </main>
    </div>
    
    <div class="footer">
      <%= render "footer.html", conn: @conn%>
    </div>

    <%= if !@conn.assigns[:secure] do %>
      <%= render "google-analytics.html" %>
      <%= render "hotjar.html" %>
    <% end %>
    <script src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/job_board_web/templates/layout/footer.html.eex
<!-- Footer -->
<footer class="page-footer pt-4">

    <!-- Footer Links -->
    <div class="container-fluid text-center text-md-left">

      <!-- Grid row -->
      <div class="row">

        <!-- Grid column -->
        <div class="col-md-9 mt-md-0 mt-3">

          <!-- Content -->
          <h5 class="text-uppercase"><%= get_site_name(@conn) %></h5>
          <p><%= "version #{get_version()}" %></p>
        </div>
        <!-- Grid column -->

        <hr class="d-md-none pb-3">
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-3 mb-md-0 mb-3">

            <!-- Links -->
            <h5 class="text-uppercase">Links</h5>

            <ul class="list-unstyled">
              <li>
                <%= link "Privacy Policy", to: Routes.page_path(@conn, :privacy) %>
              </li>
              <li>
                <%= link "Terms", to: Routes.page_path(@conn, :terms)%>
              </li>
              <li>
                <%= link "About", to: Routes.page_path(@conn, :about)%>
              </li>
            </ul>

          </div>
          <!-- Grid column -->

      </div>
      <!-- Grid row -->

    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright text-center">© 2018 Copyright:
      <a href="https://agilereaction.com"> Agile Reaction</a>
      <p>Font Awesome by Dave Gandy - <a href="http://fontawesome.io">http://fontawesome.io</a></p>
    </div>
    <!-- Copyright -->

  </footer>
  <!-- Footer -->

lib/job_board_web/templates/layout/google-analytics.html.eex
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-127319747-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-127319747-1');
</script>

lib/job_board_web/templates/layout/header.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- facebook -->
    <meta property="og:image" content="/icons/android-chrome-384x384.png" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= "#{get_current_url(@conn)}" %>" />
    <meta property="og:title" content="<%= "#{@pagetitle} | #{get_site_name(@conn)}" %>" />
    <meta property="og:description" content="<%= get_site_slug(@conn) %>" />
    

    <!-- /facebook -->

    <title><%= "#{@pagetitle} #{if @conn.assigns[:jobs] do "Page #{@conn.assigns[:jobs][:page]}" end} | #{get_site_name(@conn)}" %> </title>
    

    <link rel="apple-touch-icon" sizes="180x180" href="<%= Routes.static_path(@conn, "/icons/apple-touch-icon.png") %>">
    <link rel="icon" type="image/png" sizes="32x32" href="<%= Routes.static_path(@conn, "/icons/favicon-32x32.png") %>">
    <link rel="icon" type="image/png" sizes="16x16" href="<%= Routes.static_path(@conn, "/icons/favicon-16x16.png") %>">
    <link rel="manifest" href="<%= Routes.static_path(@conn, "/icons/site.webmanifest") %>">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
  <div class="wrapper">
    <header class="header">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <%= link get_site_name(@conn), to: Routes.job_path(@conn, :index), class: "navbar-brand"%>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
          <ul class="navbar-nav ">
            <%= if @conn.assigns[:current_user] do %>
              <li class="nav-item">
                <%= link get_post_link_text(@conn), to: Routes.job_path(@conn, :new), class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link "Profile", to: Routes.user_path(@conn, :show, @conn.assigns.current_user), class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link "Logout", to: Routes.session_path(@conn, :delete, @conn.assigns.current_user), method: "delete", class: "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link get_post_link_text(@conn), to: Routes.session_path(@conn, :new), class: "nav-link" %>
              </li>
            <% end %>
            <%= link "Contact", to: Routes.page_path(@conn, :contact), class: "nav-link" %>
          </ul>
        </div>
      </nav>
      
    </header>

lib/job_board_web/templates/layout/hotjar.html.eex
<!-- Hotjar Tracking Code for https://ohionursejobs.com/ -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:1049659,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>